In [23]:
import pandas as pd
import json

In [24]:
df_initial_posts = pd.read_csv("locationsposts_cleaned_only_location_id.csv", index_col = 0)
df_initial_posts

    user_id                                               post  location
0      3533  <p>I visited Kashmir as part of a small group ...       506
1      3533  <p>There is a report and a five-minute slidesh...       137
2      3533  <p>There is a report and a three-minute tribut...        51
3      3533  <p>With 4 other extreme travelers, I visited N...       512
4      3533  <p>There is a report and a five-minute slidesh...       296
5      3533  Tromelin is the smallest of the 4 Scattered Is...       469
6      3533  Buenos Aires is a lovely European city. My fir...       750
7      3533  There is a report and a six-minute slideshow o...       136
0         1  The Chesterfield Islands are a remote island g...         8
1         1  Annobon has an airport (a runway, anyway). The...       357
2         1  My friend Misha and I drove in a rented Land R...       558
3         1  On August 6, ten people left Apia, Samoa on a ...         4
4         1  I arrived unexpectedly to Pitcairn today, due ...        57
5         1  Swains Island is one of the furthest outposts ...       680
6         1  Rockall is probably the most difficult island ...       569
7         1  The Coral Sea Islands Territory consists of th...        13
8         1  Clipperton Island is a remote, uninhabited and...        10
9         1  My first visit to Egypt was in April, 2000. Be...       372
10        1  Market Reef is a tiny island shared between Sw...       296
11        1  Malpelo is a dramatic, barren rock some 300 mi...       172
12        1  Roughly 300 miles off the Pacific coast of Cos...       155
13        1  Chechnya is an Autonomous Republic of Russia l...       486
14        1  Franz Josef Land is an Arctic archipelago of 1...       265
15        1  Kingman Reef is a low pile of coral, roughly 4...        26
16        1  Banaba, or Ocean Island is a small, phosphorus...         5
0        53  Cruising The Kimberley<br><br>by Bill Altaffer...         3
1        53  CORRECTION: Title displays article written abo...       513
2        53  The Kingdom of Saudi Arabia<br><br>Along with ...       438
3        53  From Vladivostok to Sakhalin Island â€” rediscov...       568
4        53  Siberian Odyssey: Yenisei River Cruise<br>by B...       735
..      ...                                                ...       ...
0      7782  The Carreterra Austral photo below is a bit no...       166
2     11633  Spent a week in Vienna, highlighted by a visit...       240
3     11633  My favorite places in South Carolina have been...       140
4     11633  For a long weekend trip, I drove from New Jers...       147
5     11633  On my day trip to East Berlin in 1988, I visit...       805
6     11633  Traveled by train from Vienna to this nice tow...       316
7     11633  Had a great time that week: hopping on small p...       154
8     11633  I was having a great time in the D.R. all week...       192
9     11633  Took a bus on a day trip from Reykjavik to Gri...       230
10    11633  This was a day trip, took a ferry from Spain t...       393
11    11633  A must for visitors to Oslo, Norway, is the Fo...       302
12    11633  The marshes of Newcastle County, eastern Delaw...        93
13    11633  General store in Queen Anne, Maryland.  This w...       107
14    11633  A beautiful Spring day in downtown St.Louis, M...       113
15    11633  Driving from New Jersey to Missouri, I had to ...        99
16    11633  This building was at the far end of the main s...       101
17    11633  Burlington, Arkansas general store.  I stopped...       570
18    11633  Downtown Quapaw, Oklahoma. Quaint city hall.  ...       129
19    11633  A day trip from our house in New Jersey to Lak...       132
20    11633  Driving back to the U.S. from the airport in T...       130
21    11633  I took a day trip from Montreal to Mont Trembl...       134
22    11633  Fort Hancock, New Jersey, USA.  From the top, ...       119
23    11633  Took the Staten Island ferry to Battery Park, ...       121
24    11633  Walking around Belfast, the sun would soon dis...       276
25    11633  The harbor at Howth, Ireland. Small shops and ...       275
26    11633  Gorelovka, Republic of Georgia.  Trying to tak...       491
27    11633  Sevanavank monastery overlooking Lake Sevan, A...       476
28    11633  This was right across from the main beach. Lot...       207
0      3873  Stationed at Wheelus AB, outsite Tripoli, and ...       387
0     10097  I have been from Alexandria to Aswan and Nubia...       372

[911 rows x 3 columns]

In [26]:
df_filtering_locations = pd.read_csv("Europe_list_locations.csv")
df_filtering_locations

,Unnamed: 0,country_id,country_name,location_id,location_name,lat,lon,region_name
0,1,264,France,2,Austral Islands,-23.000000,-150.000000,Pacific Ocean
1,7,264,France,8,Chesterfield Islands,-19.350000,158.666667,Pacific Ocean
2,9,264,France,10,Clipperton Island,10.284842,-109.216250,Pacific Ocean
3,14,976,United Kingdom,15,Ducie Island,-24.680726,-124.787888,Pacific Ocean
4,18,264,France,19,Gambier Islands,-23.109658,-134.974348,Pacific Ocean
5,21,976,United Kingdom,22,Henderson Island,-24.374377,-128.327111,Pacific Ocean
6,32,264,France,33,Loyalty Islands,-21.000000,167.000000,Pacific Ocean
7,33,264,France,34,Marquesas Islands,-9.781216,-139.081712,Pacific Ocean
8,40,264,France,41,New Caledonia (mainland),-20.904305,165.618042,Pacific Ocean
9,48,976,United Kingdom,50,Oeno Island,-23.922987,-130.741200,Pacific Ocean
10,55,976,United Kingdom,57,Pitcairn Island,-25.069650,-130.122970,Pacific Ocean
11,64,264,France,66,Society Islands,-17.000000,-150.000000,Pacific Ocean
12,73,264,France,75,Tuamotu Islands,-27.566667,-144.316667,Pacific Ocean
13,78,264,France,80,Wallis and Futuna Islands,-13.295911,-176.205684,Pacific Ocean
14,136,264,France,138,St. Pierre and Miquelon,46.885200,-56.315900,North America
15,165,264,France,169,French Guiana,3.933889,-53.125782,South America
16,175,976,United Kingdom,179,Anguilla,18.220554,-63.068615,Caribbean
17,177,301,Netherlands,181,Aruba,12.521110,-69.968338,Caribbean
18,182,301,Netherlands,186,Bonaire,12.178361,-68.238534,Caribbean
19,183,976,United Kingdom,187,Cayman Islands,19.313300,-81.254600,Caribbean
20,185,301,Netherlands,189,Curacao,12.169570,-68.990020,Caribbean
21,192,264,France,196,Guadeloupe (and Deps.),16.265000,-61.551000,Caribbean
22,196,264,France,200,Martinique,14.641528,-61.024174,Caribbean
23,197,976,United Kingdom,201,Montserrat,16.742498,-62.187366,Caribbean
24,202,301,Netherlands,206,Saba,17.635464,-63.232676,Caribbean
25,204,264,France,208,St. Barths,17.900513,-62.820587,Caribbean
26,206,301,Netherlands,210,St. Eustatius,17.489031,-62.973555,Caribbean
27,209,301,Netherlands,213,St. Maarten,18.041215,-63.053073,Caribbean
28,210,264,France,214,St. Martin,18.041215,-63.053073,Caribbean
29,214,976,United Kingdom,218,Turks and Caicos Islands,21.783333,-71.733333,Atlantic Ocean
...,...,...,...,...,...,...,...,...
172,849,264,France,857,Midi-Pyrenees,44.085943,1.520862,Europe
173,850,264,France,858,Nord-Pas-de-Calais,50.480115,2.793727,Europe
174,851,264,France,859,Lower Normandy,48.878847,-0.515749,Europe
175,852,264,France,860,Upper Normandy,49.524641,0.882833,Europe
176,853,264,France,861,Pays de la Loire,47.763284,-0.329969,Europe
177,854,264,France,862,Picardy,49.663613,2.528073,Europe
178,855,264,France,863,Poitou-Charentes,45.903552,-0.309184,Europe
179,856,264,France,864,Provence-Alpes-Cote d'Azur,43.935169,6.067919,Europe
180,857,264,France,865,Rhone-Alpes,45.169580,5.450282,Europe
181,883,942,Italy,891,Abruzzo,42.192012,13.728917,Europe
182,884,942,Italy,892,Aosta Valley,45.738888,7.426187,Europe
183,885,942,Italy,893,Apulia,40.792839,17.101193,Europe
184,886,942,Italy,894,Basilicata,40.643077,15.969988,Europe
185,887,942,Italy,895,Calabria,39.308771,16.346379,Europe
186,888,942,Italy,896,Campania,41.109947,14.847514,Europe
187,889,942,Italy,897,Emilia-Romagna,44.596761,11.218640,Europe
188,890,942,Italy,898,Friuli-Venezia Giulia,46.225918,13.103365,Europe
189,891,942,Italy,899,Lazio,41.655242,12.989615,Europe
190,892,942,Italy,900,Liguria,44.316792,8.396494,Europe
191,893,942,Italy,901,Lombardy,45.479067,9.845243,Europe
192,894,942,Italy,902,Marche,43.505874,12.989615,Europe
193,895,942,Italy,903,Molise,41.630815,14.493651,Europe
194,896,942,Italy,904,Piedmont,45.050000,7.520000,Europe
195,897,942,Italy,905,Trentino-Alto Adige,46.734096,11.288801,Europe
196,898,942,Italy,906,Tuscany,43.771051,11.248621,Europe
197,899,942,Italy,907,Umbria,42.938004,12.621621,Europe
198,900,942,Italy,908,Veneto,45.762333,11.690976,Europe
199,912,264,France,999,Matthew and Hunter Islands (and Walpole),-22.369823,171.438762,Pacific Ocean
200,913,976,United Kingdom,1000,Outer Hebrides,57.936588,-9.472554,Europe
201,914,976,United Kingdom,1001,St. Kilda,57.813445,-8.618827,Europe

In [27]:
df_final_posts = df_initial_posts[df_initial_posts.location.isin(df_filtering_locations.location_id)]
df_final_posts

     user_id                                               post  location
4       3533  <p>There is a report and a five-minute slidesh...       296
5       3533  Tromelin is the smallest of the 4 Scattered Is...       469
0          1  The Chesterfield Islands are a remote island g...         8
4          1  I arrived unexpectedly to Pitcairn today, due ...        57
6          1  Rockall is probably the most difficult island ...       569
8          1  Clipperton Island is a remote, uninhabited and...        10
10         1  Market Reef is a tiny island shared between Sw...       296
8        111  <p>I have visited Paris several times, includi...       853
11       111  <p>November 2018 -- I spent a few days in Amst...       301
50       111  November 2017 -- I made a day trip from Paris ...       861
62       111  September 2017 -- I traveled by ferry from Tur...       236
83       111  June 2017 -- I spent a few days in Wallis and ...        80
87       111  September 2016 -- I based myself in Hildesheim...       810
88       111  September 2016 -- While traveling by train fro...       807
89       111  September 2016 -- I made a day trip by high sp...       799
90       111  September 2016 -- I began my trip in Stralsund...       811
91       111  September 2016 -- I visited the Neues Palais (...       806
92       111  September 2016 -- I based myself in Lutherstad...       816
93       111  September 2016 -- I visited Leipzig, the large...       815
94       111  September 2016 -- I visited several of the con...       818
99       111  August 2016 -- I stayed at HÃ´tel Le Rocher in ...       462
120      111  September 2015 -- I spent three days in Bari, ...       893
121      111  September 2015 -- I made a day trip from Bari ...       894
122      111  September 2015 -- I spent three nights in Cagl...       309
123      111  September 2015 -- I rented a scooter to circum...       286
126      111  May 2015 -- I visited Bratislava, where I rent...       316
130      111  November 2014 -- I began my trip in MÃ©rida, wh...       840
131      111  November 2014 -- I made a day trip by ferry (h...       366
132      111  November 2014 -- I made a day trip by plane fr...       392
133      111  November 2014 -- I visited Murcia, the capital...       843
..       ...                                                ...       ...
0      31221  Over three times the size of Texas, Greenland ...       229
3      31221  An island that is part of Netherlands lies abo...       206
1         35  First of all, I like traveling to any place wh...       305
3         35  I was in Copenhagen for a few days in July 199...       258
9         35  The Society Islands are 1 of 5 island groups t...        66
12        35  My wife and I vistited the BVI during a two we...       220
16        35  My wife and I honeymooned in French Polynesia ...        75
22        35  We hopped on over to Sao Miguel from Lisbon fo...       222
0      14937  My ship, the MV Houston, brought containerized...       221
16      2297  My only trip to Hesse (so far) was a long layo...       809
54      2297  In April, 2002, my new bride, Karen, and I fle...       260
57      2297  I visited the Caribbean island nation of Angui...       179
59      2297  My wife Karen and I visited the island of Cura...       189
61      2297  After our wedding in early spring, 2002, my ne...       328
63      2297  I visited Bonaire, in the Caribbean Netherland...       186
72      2297  On March 17, 2010, I visited Aruba with my wif...       181
90      2297  Karen and I celebrated our honeymoon with a te...       312
98      2297  Karen and I traveled to the Cayman Islands twi...       187
6       5417  Tallinn is an interesting city but can easily ...       261
7       5417  Lisbon and surroundings (Sintra, Estoril, Casc...       305
8       5417  Nice constant breeze so never too hot. Nice be...       181
7       2701  Well, they say Iceland is green and Greenland ...       229
9       2701  A, B, C islands, well that is what the Dutch c...       189
10      2701  A, B, C islands, well that is what the Dutch c...       186
11      2701  A, B, C islands, well that is what the Dutch c...       181
0       8070  Still my favorite beach on the planet, where y...       218
2      11633  Spent a week in Vienna, highlighted by a visit...       240
5      11633  On my day trip to East Berlin in 1988, I visit...       805
6      11633  Traveled by train from Vienna to this nice tow...       316
24     11633  Walking around Belfast, the sun would soon dis...       276

[200 rows x 3 columns]

In [28]:
df_final_posts.to_csv("cleaned_posts_only_europe.csv")