In [6]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [7]:
rf = RandomForestClassifier(n_estimators=200)

In [8]:
data = pd.read_csv('raw_datawithstate_mock_1.csv')
data = data.filter(["Age","gender","state","country_name"])
x_data=data.loc[:,["Age","gender","state"]]
y_data = data.loc[:,"country_name"]
y_data

0              Austria
1               France
2             Portugal
3                Italy
4       United Kingdom
5              Ireland
6       United Kingdom
7                Italy
8              Finland
9                Italy
10             Finland
11             Germany
12               Spain
13      United Kingdom
14             Denmark
15             Denmark
16               Spain
17             Germany
18               Italy
19              France
20               Malta
21               Spain
22               Spain
23            Slovakia
24             Germany
25              France
26             Austria
27            Slovakia
28            Bulgaria
29             Germany
             ...
1657    United Kingdom
1658             Italy
1659             Spain
1660           Germany
1661          Bulgaria
1662            France
1663           Germany
1664             Spain
1665             Spain
1666             Italy
1667           Finland
1668           Denmark
1669    United Kingdom
1670             Italy
1671    United Kingdom
1672             Spain
1673           Finland
1674            France
1675           Ireland
1676            Greece
1677    United Kingdom
1678            France
1679            France
1680           Ireland
1681          Bulgaria
1682            Greece
1683           Germany
1684             Italy
1685          Bulgaria
1686    United Kingdom
Name: country_name, Length: 1687, dtype: object

In [9]:
for x in x_data.gender.unique():
    x_data[x]=[1 if y == x else 0 for y in x_data.gender]
x_data

      Age gender           state  M  F
0      81      M        Illinois  1  0
1      74      M        Illinois  1  0
2      53      M      California  1  0
3      75      M      California  1  0
4      68      M        Illinois  1  0
5      74      M      California  1  0
6      75      M      California  1  0
7      83      M        New York  1  0
8      45      M       Wisconsin  1  0
9      73      M      California  1  0
10     81      M      California  1  0
11     57      M         Alabama  1  0
12     82      M            Ohio  1  0
13     61      M      California  1  0
14     50      F      California  0  1
15     77      M      California  1  0
16     72      M  North Carolina  1  0
17     70      M        Illinois  1  0
18     79      M         Florida  1  0
19     87      F      California  0  1
20     55      F        New York  0  1
21     81      M      California  1  0
22     77      M          Kansas  1  0
23     55      M        New York  1  0
24     83      M      California  1  0
25     59      M        New York  1  0
26     68      M      California  1  0
27     92      F  North Carolina  0  1
28     70      M        Missouri  1  0
29     78      M          Oregon  1  0
...   ...    ...             ... .. ..
1657   42      M        Missouri  1  0
1658   44      M        Maryland  1  0
1659   47      M         Arizona  1  0
1660   49      M           Texas  1  0
1661   53      M         Florida  1  0
1662   56      M  North Carolina  1  0
1663   59      M      California  1  0
1664   64      F           Texas  0  1
1665   74      F          Nevada  0  1
1666   75      M        Maryland  1  0
1667   77      M         Georgia  1  0
1668   79      M        Illinois  1  0
1669   93      M        New York  1  0
1670    7      M        New York  1  0
1671   33      F      California  0  1
1672   37      M       Wisconsin  1  0
1673   42      M      California  1  0
1674   46      M      California  1  0
1675   46      M    Pennsylvania  1  0
1676   47      M        New York  1  0
1677   50      M           Texas  1  0
1678   53      M        Illinois  1  0
1679   58      F        New York  0  1
1680   59      M      California  1  0
1681   60      M            Ohio  1  0
1682   64      M      California  1  0
1683   64      F         Florida  0  1
1684   69      M        Michigan  1  0
1685   74      M        Oklahoma  1  0
1686   87      F         Florida  0  1

[1687 rows x 5 columns]

In [10]:
for x in x_data.state.unique():
    x_data[x]=[1 if y == x else 0 for y in x_data.state]
x_data = x_data.drop(columns =["gender","state"])
x_data

,Age,M,F,Illinois,California,New York,Wisconsin,Alabama,Ohio,North Carolina,...,Arkansas,New Hampshire,Tennessee,Alaska,Nebraska,Delaware,Iowa,Rhode Island,South Dakota,Montana
0,81,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,74,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,53,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,75,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,68,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,74,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,75,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,83,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,45,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,73,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,81,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,57,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,82,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13,61,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,50,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,77,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,72,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,70,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,79,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,87,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,55,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,81,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,77,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,55,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,83,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,59,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,68,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,92,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,70,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,78,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1657,42,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1658,44,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1659,47,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1660,49,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1661,53,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1662,56,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1663,59,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1664,64,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1665,74,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1666,75,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1667,77,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1668,79,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1669,93,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1670,7,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1671,33,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1672,37,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1673,42,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1674,46,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1675,46,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1676,47,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1677,50,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,53,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1679,58,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1680,59,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,60,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1682,64,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1683,64,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1684,69,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1685,74,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1686,87,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
y_data

0              Austria
1               France
2             Portugal
3                Italy
4       United Kingdom
5              Ireland
6       United Kingdom
7                Italy
8              Finland
9                Italy
10             Finland
11             Germany
12               Spain
13      United Kingdom
14             Denmark
15             Denmark
16               Spain
17             Germany
18               Italy
19              France
20               Malta
21               Spain
22               Spain
23            Slovakia
24             Germany
25              France
26             Austria
27            Slovakia
28            Bulgaria
29             Germany
             ...
1657    United Kingdom
1658             Italy
1659             Spain
1660           Germany
1661          Bulgaria
1662            France
1663           Germany
1664             Spain
1665             Spain
1666             Italy
1667           Finland
1668           Denmark
1669    United Kingdom
1670             Italy
1671    United Kingdom
1672             Spain
1673           Finland
1674            France
1675           Ireland
1676            Greece
1677    United Kingdom
1678            France
1679            France
1680           Ireland
1681          Bulgaria
1682            Greece
1683           Germany
1684             Italy
1685          Bulgaria
1686    United Kingdom
Name: country_name, Length: 1687, dtype: object

In [12]:

rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(x_data, y_data)
rf.score(x_data, y_data)

0.6893894487255483

In [13]:
rf.feature_importances_

array([7.46663415e-01, 1.93342671e-02, 1.90195346e-02, 6.78427836e-03,
       1.09563315e-02, 1.02119353e-02, 5.27751369e-03, 3.36229585e-03,
       4.53714906e-03, 5.59155908e-03, 9.32026428e-03, 2.38712349e-03,
       4.90515637e-03, 5.93673621e-03, 7.47169339e-03, 4.22617857e-03,
       2.91888331e-03, 5.16511493e-03, 5.40574443e-03, 3.50810613e-03,
       4.78180303e-03, 5.66818639e-03, 5.95434848e-03, 4.70954660e-03,
       5.82400533e-03, 4.96957878e-03, 5.91317397e-03, 4.20986953e-03,
       6.75235413e-03, 2.65560174e-03, 7.56678498e-03, 2.05362234e-03,
       5.34432221e-03, 7.57449632e-03, 5.50457167e-03, 1.63482634e-03,
       4.68502631e-03, 1.25788233e-03, 2.24648519e-03, 2.22594913e-03,
       4.49416771e-03, 2.26733928e-03, 2.97707582e-03, 3.13523453e-03,
       3.75140635e-03, 6.37655419e-04, 1.81395727e-03, 2.40240993e-03,
       6.04956875e-04, 1.81162930e-03, 8.14794288e-04, 7.73658036e-04])

In [16]:
x_header = list(x_data.columns.values)
x_header

['Age',
 'M',
 'F',
 'Illinois',
 'California',
 'New York',
 'Wisconsin',
 'Alabama',
 'Ohio',
 'North Carolina',
 'Florida',
 'Kansas',
 'Missouri',
 'Oregon',
 'Texas',
 'Nevada',
 'Louisiana',
 'District of Columbia',
 'Maryland',
 'Oklahoma',
 'Indiana',
 'Colorado',
 'Washington',
 'Utah',
 'Minnesota',
 'Michigan',
 'Georgia',
 'Connecticut',
 'Arizona',
 'Mississippi',
 'Virginia',
 'Kentucky',
 'Pennsylvania',
 'Massachusetts',
 'New Jersey',
 'West Virginia',
 'South Carolina',
 'Idaho',
 'New Mexico',
 'Maine',
 'Hawaii',
 'Vermont',
 'Arkansas',
 'New Hampshire',
 'Tennessee',
 'Alaska',
 'Nebraska',
 'Delaware',
 'Iowa',
 'Rhode Island',
 'South Dakota',
 'Montana']

In [32]:

x_dataforprediction = [80,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0]
x_prediction = pd.DataFrame(columns = x_header)
x_prediction.loc[len(x_prediction)]=x_dataforprediction
x_prediction

,Age,M,F,Illinois,California,New York,Wisconsin,Alabama,Ohio,North Carolina,...,Arkansas,New Hampshire,Tennessee,Alaska,Nebraska,Delaware,Iowa,Rhode Island,South Dakota,Montana
0,80,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [29]:
y_prediction=rf.predict(x_prediction)
y_prediction

array(['Spain'], dtype=object)

In [34]:
#save the model
# clf.save("Euro_trivia.h5")

import pickle

filename = 'rf.sav'
pickle.dump(rf, open(filename, 'wb'))

In [ ]:
# load model from disk

import pickle

filename = 'rf.sav'
loaded_model = pickle.load(open(filename, 'rb'))