In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [2]:
rf = RandomForestClassifier(n_estimators=200)

In [61]:
data = pd.read_csv('final_data_forML.csv')
data = data.filter(["Age","gender","state","country_name"])
x_data=data.loc[:,["Age","gender","state"]]
y_data = data.loc[:,"country_name"]
y_data

0     United Kingdom
1             France
2           Portugal
3           Portugal
4              Italy
5              Italy
6        Netherlands
7              Spain
8              Italy
9              Italy
10             Italy
11           Denmark
12           Denmark
13    United Kingdom
14    United Kingdom
15            France
16    Czech Republic
17    Czech Republic
18    Czech Republic
19        Luxembourg
20             Italy
21    United Kingdom
22    United Kingdom
23             Spain
24             Spain
25             Italy
26           Germany
27             Italy
28             Italy
29           Germany
30            Greece
31    United Kingdom
32    United Kingdom
33    United Kingdom
34    United Kingdom
35           Croatia
36            France
37    United Kingdom
38    United Kingdom
39           Romania
Name: country_name, dtype: object

In [63]:
for x in x_data.gender.unique():
    x_data[x]=[1 if y == x else 0 for y in x_data.gender]
x_data

    Age gender           state  M  F
0    54      M      California  1  0
1    68      M         Florida  1  0
2    42      M      California  1  0
3    67      M       Tennessee  1  0
4    55      M        New York  1  0
5    53      M      California  1  0
6    40      M        Illinois  1  0
7    48      M           Texas  1  0
8    74      M       Tennessee  1  0
9    72      M      California  1  0
10   42      M      California  1  0
11   47      M      New Jersey  1  0
12   52      M      California  1  0
13   33      F        Oklahoma  0  1
14   41      F           Texas  0  1
15   74      M        Illinois  1  0
16   38      F      California  0  1
17   39      M         Florida  1  0
18   48      M        Illinois  1  0
19   47      M        Virginia  1  0
20   63      M         Florida  1  0
21   63      M         Georgia  1  0
22   44      M         Georgia  1  0
23   31      M      California  1  0
24   27      M        Michigan  1  0
25   55      F    Pennsylvania  0  1
26   59      M      New Jersey  1  0
27   75      F   West Virginia  0  1
28   54      M    Pennsylvania  1  0
29   75      M      California  1  0
30   28      M       Minnesota  1  0
31   43      M       Louisiana  1  0
32   61      M         Florida  1  0
33   72      M        Colorado  1  0
34   51      M          Hawaii  1  0
35   39      M  North Carolina  1  0
36   35      F        New York  0  1
37   21      M      New Jersey  1  0
38   23      M       Wisconsin  1  0
39   37      M      California  1  0

In [67]:
for x in x_data.state.unique():
    x_data[x]=[1 if y == x else 0 for y in x_data.state]
x_data = x_data.drop(columns =["gender","state"])
x_data

,Age,M,F,California,Florida,Tennessee,New York,Illinois,Texas,New Jersey,...,Georgia,Michigan,Pennsylvania,West Virginia,Minnesota,Louisiana,Colorado,Hawaii,North Carolina,Wisconsin
0,54,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,68,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,42,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,67,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,55,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,53,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,40,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,48,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,74,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,72,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,42,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,47,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,52,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,33,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,41,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,74,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,38,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,39,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,48,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19,47,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,63,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,63,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22,44,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23,31,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,27,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25,55,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
26,59,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,75,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,54,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29,75,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,28,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
31,43,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32,61,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,72,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
34,51,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
35,39,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
36,35,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,21,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
38,23,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,37,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
y_data

0     United Kingdom
1             France
2           Portugal
3           Portugal
4              Italy
5              Italy
6        Netherlands
7              Spain
8              Italy
9              Italy
10             Italy
11           Denmark
12           Denmark
13    United Kingdom
14    United Kingdom
15            France
16    Czech Republic
17    Czech Republic
18    Czech Republic
19        Luxembourg
20             Italy
21    United Kingdom
22    United Kingdom
23             Spain
24             Spain
25             Italy
26           Germany
27             Italy
28             Italy
29           Germany
30            Greece
31    United Kingdom
32    United Kingdom
33    United Kingdom
34    United Kingdom
35           Croatia
36            France
37    United Kingdom
38    United Kingdom
39           Romania
Name: country_name, dtype: object

In [68]:
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(x_data, y_data)
rf.score(x_data, y_data)

0.975

In [69]:
rf.feature_importances_

array([0.42533802, 0.02747932, 0.02574595, 0.06484063, 0.03774564,
       0.03037675, 0.03122296, 0.0539655 , 0.02952426, 0.03946746,
       0.01068826, 0.02998525, 0.02970916, 0.02233227, 0.02592512,
       0.00999319, 0.02675838, 0.01164835, 0.01634045, 0.0147324 ,
       0.02327156, 0.01290913])